
package services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookService", targetNamespace = "http://services/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookService {


    /**
     * 
     * @param createRequest
     * @return
     *     returns services.CreateResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services/BookService/createRequest", output = "http://services/BookService/createResponse")
    public CreateResponse create(
        @WebParam(name = "createRequest", partName = "createRequest")
        CreateRequest createRequest);

    /**
     * 
     * @param findByNameRequest
     * @return
     *     returns services.FindByNameResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services/BookService/findByNameRequest", output = "http://services/BookService/findByNameResponse")
    public FindByNameResponse findByName(
        @WebParam(name = "findByNameRequest", partName = "findByNameRequest")
        FindByNameRequest findByNameRequest);

}
